spring:
  datasource:
    url: jdbc:postgresql://dpg-d7ic32navr4c73file40-a/uzbek_transliterator_db
    username: uzbek_transliterator_db_user
    password: DFfvrlq6flEq2UBy8UaZfx1i5yw0Vth0
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}

bot:
  username: uzbek_translit_bot
  token: 8478504038:AAGTZK6oXiIGHtlZfKgB9aTfnwWB33Li2jU
