spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/uzbek_transliterator}}
    username: ${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:963}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}

bot:
  username: ${BOT_USERNAME:uzbek_translit_bot}
  token: ${BOT_TOKEN:8478504038:AAGTZK6oXiIGHtlZfKgB9aTfnwWB33Li2jU}
